name: Build and deploy ASP.Net Core app to Azure Web App - WebAppAndDataBase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      # --- EF CORE MIGRATIONS (г юбрноньсйнл) ---
      - name: Install EF Core Tool
        run: dotnet tool install -g dotnet-ef --version 7.0.14

      - name: Create migration bundle
        run: |
          PROJECT_PATH=$(find . -name "*.csproj" -print -quit)
          echo "Found project at: $PROJECT_PATH"
          dotnet ef migrations bundle --runtime linux-x64 -p "$PROJECT_PATH" -o ${{env.DOTNET_ROOT}}/myapp/migrate
      # ------------------------------------------

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
 
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B5AFA80FAE904C839F9FB3F843CF5EAA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C3A4228D315C40D485B85331B590AF20 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D3A2A5EAFCAE409C9AEDB15B44F63E1A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WebAppAndDataBase'
          slot-name: 'Production'
          package: .